### ISSUE TITLE
チェックスクリプトをmasterブランチに統合するかどうか

### ISSUE THREAD

**Issue by Tiryoh** [rt-net/raspicat_setup_scripts#3]
チェックスクリプトは出荷時にロボットに同梱されるマニュアルに書いていなかったのでmasterブランチに統合していませんでした。
今後チェックスクリプトに関してここでメンテナンスしていくようであればmasterブランチに統合してマニュアルに簡単な説明を追記するのもよいかと思っています。
@ShotaAk いかがでしょうか。

**Comment by ShotaAk** [comment]
masterと統合しましょう。
